defaults: &defaults
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: password
  template: template0 # Required for UTF8 encoding

development:
  <<: *defaults
  database: Mediator_development

test:
  <<: *defaults
  database: Mediator_test

production:
  <<: *defaults
  database: Mediator_production
